version: '3'

services:
  app:
    build:
      context: ./app
      args:
        - PHP_VERSION=${PHP_VERSION}
        - APP_CONTAINER_PATH=${APP_CONTAINER_PATH}
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
        - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
    volumes:
      - ..:${APP_CONTAINER_PATH}
      - ./logs/app:${APP_CONTAINER_PATH}/${APP_NAME}/storage/logs
    depends_on:
      - db
  
  nginx:
    build:
      context: ./nginx
      args:
        - APP_NAME=${APP_NAME}
        - APP_CONTAINER_PATH=${APP_CONTAINER_PATH}
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ..:${APP_CONTAINER_PATH}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - app

  db:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./logs/db:/var/log/mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"