version: '3'

services:
  app:
    build:
      context: ./app
      args:
        - PHP_VERSION=${PHP_VERSION}
        - APP_CONTAINER_PATH=${APP_CONTAINER_PATH}
    volumes:
      - .:${APP_CONTAINER_PATH}
  
  nginx:
    build:
      context: ./nginx
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - app